# Generated by Django 3.1.1 on 2020-10-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title not available', max_length=200)),
                ('head0', models.CharField(default='Heading 0', max_length=200)),
                ('head1', models.CharField(default='Heading 1', max_length=200)),
                ('head2', models.CharField(default='Heading 2', max_length=200)),
                ('pubdt', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
