# Generated by Django 3.1.1 on 2020-10-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201001_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
