# Generated by Django 3.1.1 on 2020-10-05 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201004_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField()),
                ('state', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('zipcode', models.IntegerField()),
                ('orderdt', models.DateTimeField()),
                ('orderstatus', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 11, 20, 25, 691786), max_length=20),
        ),
    ]
