# Generated by Django 3.1.1 on 2020-10-05 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201005_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestap', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 23, 15, 12, 211575), max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 23, 15, 12, 211575)),
        ),
    ]
