# Generated by Django 3.1.1 on 2020-10-06 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201005_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestap',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='contact',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 7, 53, 2, 139887), max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 7, 53, 2, 139887)),
        ),
    ]
