# Generated by Django 3.1.1 on 2020-10-07 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201006_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 7, 25, 162774), max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 7, 25, 162774)),
        ),
    ]
