# Generated by Django 3.1.1 on 2020-10-07 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201007_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 11, 16, 207721), max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 20, 11, 16, 208722)),
        ),
    ]
