# Generated by Django 3.1.1 on 2020-10-07 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201007_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 22, 26, 56, 315740), max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderdt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 22, 26, 56, 315740)),
        ),
    ]
